{
 "title": "TelematicsTracker",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, speed FROM gps ORDER BY timestamp_ DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Acceleration Log",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ AS \"Timestamp\", event_ AS \"Event Type\", x_accel AS \"X Acceleration\", y_accel AS \"Y Acceleration\" FROM accel ORDER BY timestamp_ DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "SOS Log",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ AS \"Timestamp\", event_ AS \"Alert\" FROM sos ORDER BY timestamp_ DESC LIMIT 5 "
    }
   ]
  },
  {
   "title": "Speedometer",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT speed FROM gps ORDER BY timestamp_ DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Latest Location Update Times",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp_ AS \"Timestamp\", latitude AS \"Latitude\", longitude AS \"Longitude\" FROM gps ORDER BY timestamp_ DESC LIMIT 5 "
    }
   ]
  }
 ]
}